print("Please enter the following: ")
print('')
adjective = input("adjective: ")
animal = input("animal: ")
verb = input("verb: ")
exclamation = input("exclamation: ")
verb2 = input("verb: ")
verb3 = input("verb: ")
adjective2 = input("adjective: ")
animal2 = input("animal: ")
verb4 = input("verb: ")
print('')
print('your story is: ')
print('')
output = f'The other day I was really in trouble. it all started when a saw a very {adjective}, {animal}, {verb} down the hallway. "{exclamation}!" I yelled. But all I could think to do was to {verb2} over and over. Miraculously, that caused it to stop but not before it tried to {verb3} right in front of my family. I realized that it was all a dream, so I woke up and pet my {animal2}. I went outside and saw a {adjective2} ball that I kicked so far way, and I {verb4} untill nigth.'
print(output)