name=input("What is your name?: ")
print(f"Hello {name}")
place=input(f"Where are you from: ")
print(f"{place},is a great place {name}")
color=input(f"what is your favorite color?,{name}: ")
print(f"{name}, your favorite color is {color}")
print(f"Have a good day {name}")